####GET Orders2
GET http://localhost:4004/manage-orders/GetOrders

####GET Order2
GET http://localhost:4004/manage-orders/GetOrders('client1@client1.com')

####CREATE Order2
POST http://localhost:4004/manage-orders/CreateOrder
Content-Type: application/json

{
    "ClientEmail": "Client5@client5.com", 
    "FirstName" : "Lorena", 
    "LastName" : "Garcia",
    "CreatedOn" : "2024-10-10"
}
 
####UPDATE Order2
PUT http://localhost:4004/manage-orders/UpdateOrder('client4@client4.com') HTTP/1.1
Content-Type: application/json

{ 
    "FirstName" : "Albert", 
    "LastName" : "Einstein"
} 

####DELETE Order2
DELETE http://localhost:4004/manage-orders/DeleteOrder('client4@client4.com') HTTP/1.1

####GET Customer Rate - Function
GET http://localhost:4004/manage-orders/getClientTaxRate(ClientEmail='client4@client4.com') HTTP/1.1

####Cancel Order - Action 
POST http://localhost:4004/manage-orders/CancelOrder  
Content-Type: application/json

{
    "ClientEmail" : "client2@client2.com"
}
